#!/usr/bin/env python3
"""Layer B reproduction check for the VFSS_analysis pilot.

Compares the parameter CSVs regenerated by run.py (--new) against the authors'
provided reference CSVs (--ref, backed up before the run). Segmentation->parameter
extraction is expected to be deterministic, so a faithful re-execution should
reproduce these values near-exactly.

Verdict: FULLY REPRODUCIBLE (all shared CSVs match within tolerance) /
         PARTIAL / NOT REPRODUCED / NO OUTPUT.
"""
import argparse, glob, os, sys
import numpy as np
import pandas as pd


def load(path):
    df = pd.read_csv(path)
    # Drop an unnamed leading index column if present (e.g., hyoid_elevation.csv).
    if str(df.columns[0]).startswith("Unnamed"):
        df = df.drop(columns=df.columns[0])
    return df


def compare_file(ref_path, new_path, atol, rtol):
    r, n = load(ref_path), load(new_path)
    cols = [c for c in r.columns if c in n.columns]
    rows = min(len(r), len(n))
    per_col, worst = {}, 0.0
    for c in cols:
        a = pd.to_numeric(r[c], errors="coerce").to_numpy()[:rows]
        b = pd.to_numeric(n[c], errors="coerce").to_numpy()[:rows]
        diff = np.abs(a - b)
        mx = float(np.nanmax(diff)) if diff.size else float("nan")
        within = bool(np.allclose(a, b, atol=atol, rtol=rtol, equal_nan=True))
        per_col[c] = (mx, within)
        if not np.isnan(mx):
            worst = max(worst, mx)
    shape_match = (r.shape == n.shape)
    file_ok = shape_match and all(w for _, w in per_col.values()) and len(per_col) > 0
    return file_ok, shape_match, len(r), len(n), worst


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", required=True, help="dir with reference CSVs")
    ap.add_argument("--new", required=True, help="dir with regenerated CSVs")
    ap.add_argument("--atol", type=float, default=1e-6)
    ap.add_argument("--rtol", type=float, default=1e-3)
    a = ap.parse_args()

    ref_files = sorted(glob.glob(os.path.join(a.ref, "*.csv")))
    if not ref_files:
        print(f"No reference CSVs in {a.ref}"); sys.exit(2)

    print("== Layer B reproduction check (VFSS_analysis / healthy_001) ==")
    print(f"tolerance: atol={a.atol} rtol={a.rtol}\n")
    all_ok, any_file = True, False
    for rf in ref_files:
        name = os.path.basename(rf)
        nf = os.path.join(a.new, name)
        if not os.path.exists(nf):
            print(f"[MISSING] {name}: not regenerated"); all_ok = False; continue
        any_file = True
        ok, shp, nr, nn, worst = compare_file(rf, nf, a.atol, a.rtol)
        all_ok &= ok
        tag = "OK  " if ok else "DIFF"
        print(f"[{tag}] {name}: shape_match={shp} rows ref/new={nr}/{nn} max_abs_diff={worst:.4g}")

    verdict = ("FULLY REPRODUCIBLE" if (all_ok and any_file)
               else "NOT REPRODUCED / PARTIAL" if any_file else "NO OUTPUT")
    print(f"\nVERDICT: {verdict}")
    sys.exit(0 if (all_ok and any_file) else 1)


if __name__ == "__main__":
    main()
